export const userConstants = {
  LOAD_USERS: 'LOAD_USERS',
  LOAD_USERS_FAIL: 'LOAD_USERS_FAIL',
  LOAD_PROFILES: 'LOAD_PROFILES',
  LOAD_PROFILES_FAIL: 'LOAD_PROFILES_FAIL',
  GET_USERS: 'GET_USERS',
  GET_USER_PROFILES: 'GET_USER_PROFILES',
};
